<script type="text/x-magento-init">
{
    "*": {
        "my-widget-first": {
            "name": "<?= __('bar') ?>"
        }
    }
}
</script>

<button class="button" id="button">Click Me!</button>

<script type="text/x-magento-init">
{
    "#button": {
        "my-widget-second": {
            "name": "<?= __('baz') ?>"
        }
    }
}
</script>

<div

<button
    data-mage-init='{"my-widget-second":{"name":"foo"}}'
    class="button" id="enter">Click Me Now!</button>
